# Webscraping using BeautifulSoup

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
Book_info=[]
url="https://books.toscrape.com/"
r=requests.get(url)
r

In [3]:
soup=BeautifulSoup(r.content,'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [4]:
book=soup.find_all('li',class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")
book[:1]

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [5]:
for item in book:
  name_tag=item.find('h3').find('a')
  book_name=name_tag.text
  book_link=name_tag['href']
  price=item.find('p',class_="price_color").text
  stock=item.find('p',class_="instock availability").text.strip()
  rating=item.find('p',class_="star-rating")['class'][1]

  row={
      'Book_Name':book_name,
      "Book_Link":book_link,
      'price':price,
      'stock':stock,
      'rating':rating
  }
  Book_info.append(row)

In [6]:
df=pd.DataFrame(Book_info)
df

,Book_Name,Book_Link,price,stock,rating
0,A Light in the ...,catalogue/a-light-in-the-attic_1000/index.html,£51.77,In stock,Three
1,Tipping the Velvet,catalogue/tipping-the-velvet_999/index.html,£53.74,In stock,One
2,Soumission,catalogue/soumission_998/index.html,£50.10,In stock,One
3,Sharp Objects,catalogue/sharp-objects_997/index.html,£47.82,In stock,Four
4,Sapiens: A Brief History ...,catalogue/sapiens-a-brief-history-of-humankind...,£54.23,In stock,Five
5,The Requiem Red,catalogue/the-requiem-red_995/index.html,£22.65,In stock,One
6,The Dirty Little Secrets ...,catalogue/the-dirty-little-secrets-of-getting-...,£33.34,In stock,Four
7,The Coming Woman: A ...,catalogue/the-coming-woman-a-novel-based-on-th...,£17.93,In stock,Three
8,The Boys in the ...,catalogue/the-boys-in-the-boat-nine-americans-...,£22.60,In stock,Four
9,The Black Maria,catalogue/the-black-maria_991/index.html,£52.15,In stock,One
10,Starving Hearts (Triangular Trade ...,catalogue/starving-hearts-triangular-trade-tri...,£13.99,In stock,Two
11,Shakespeare's Sonnets,catalogue/shakespeares-sonnets_989/index.html,£20.66,In stock,Four
12,Set Me Free,catalogue/set-me-free_988/index.html,£17.46,In stock,Five
13,Scott Pilgrim's Precious Little ...,catalogue/scott-pilgrims-precious-little-life-...,£52.29,In stock,Five
14,Rip it Up and ...,catalogue/rip-it-up-and-start-again_986/index....,£35.02,In stock,Five
15,Our Band Could Be ...,catalogue/our-band-could-be-your-life-scenes-f...,£57.25,In stock,Three
16,Olio,catalogue/olio_984/index.html,£23.88,In stock,One
17,Mesaerion: The Best Science ...,catalogue/mesaerion-the-best-science-fiction-s...,£37.59,In stock,One
18,Libertarianism for Beginners,catalogue/libertarianism-for-beginners_982/ind...,£51.33,In stock,Two
19,It's Only the Himalayas,catalogue/its-only-the-himalayas_981/index.html,£45.17,In stock,Two

In [10]:
dict1={
    'one':1,'two':2,'three':3,'four':4,'five':5
}
def f(a):
  return dict1[a.lower()]
df['rating']=df['rating'].apply(f)
df

,Book_Name,Book_Link,price,stock,rating
0,A Light in the ...,catalogue/a-light-in-the-attic_1000/index.html,£51.77,In stock,3
1,Tipping the Velvet,catalogue/tipping-the-velvet_999/index.html,£53.74,In stock,1
2,Soumission,catalogue/soumission_998/index.html,£50.10,In stock,1
3,Sharp Objects,catalogue/sharp-objects_997/index.html,£47.82,In stock,4
4,Sapiens: A Brief History ...,catalogue/sapiens-a-brief-history-of-humankind...,£54.23,In stock,5
5,The Requiem Red,catalogue/the-requiem-red_995/index.html,£22.65,In stock,1
6,The Dirty Little Secrets ...,catalogue/the-dirty-little-secrets-of-getting-...,£33.34,In stock,4
7,The Coming Woman: A ...,catalogue/the-coming-woman-a-novel-based-on-th...,£17.93,In stock,3
8,The Boys in the ...,catalogue/the-boys-in-the-boat-nine-americans-...,£22.60,In stock,4
9,The Black Maria,catalogue/the-black-maria_991/index.html,£52.15,In stock,1
10,Starving Hearts (Triangular Trade ...,catalogue/starving-hearts-triangular-trade-tri...,£13.99,In stock,2
11,Shakespeare's Sonnets,catalogue/shakespeares-sonnets_989/index.html,£20.66,In stock,4
12,Set Me Free,catalogue/set-me-free_988/index.html,£17.46,In stock,5
13,Scott Pilgrim's Precious Little ...,catalogue/scott-pilgrims-precious-little-life-...,£52.29,In stock,5
14,Rip it Up and ...,catalogue/rip-it-up-and-start-again_986/index....,£35.02,In stock,5
15,Our Band Could Be ...,catalogue/our-band-could-be-your-life-scenes-f...,£57.25,In stock,3
16,Olio,catalogue/olio_984/index.html,£23.88,In stock,1
17,Mesaerion: The Best Science ...,catalogue/mesaerion-the-best-science-fiction-s...,£37.59,In stock,1
18,Libertarianism for Beginners,catalogue/libertarianism-for-beginners_982/ind...,£51.33,In stock,2
19,It's Only the Himalayas,catalogue/its-only-the-himalayas_981/index.html,£45.17,In stock,2

In [17]:
df.to_csv("Book_info.csv")

# All page data scrap

In [13]:
Book_info_all=[]
dict1={
    'one':1,'two':2,'three':3,'four':4,'five':5
}
for i in range(1,51):
  url_all=f"https://books.toscrape.com/catalogue/page-{i}.html"
  r=requests.get(url_all)
  soup=BeautifulSoup(r.content,'html.parser')
  book=soup.find_all('li',class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")
  for item in book:
    name_tag=item.find('h3').find('a')
    book_name=name_tag.text
    book_link=name_tag['href']
    price=item.find('p',class_="price_color").text
    stock=item.find('p',class_="instock availability").text.strip()
    rating=item.find('p',class_="star-rating")['class'][1]

    row={
        'Book_Name':book_name,
        "Book_Link":book_link,
        'price':price,
        'stock':stock,
        'rating':dict1[rating.lower()]
    }
    Book_info_all.append(row)

In [14]:
df_all=pd.DataFrame(Book_info_all)
df_all

,Book_Name,Book_Link,price,stock,rating
0,A Light in the ...,a-light-in-the-attic_1000/index.html,£51.77,In stock,3
1,Tipping the Velvet,tipping-the-velvet_999/index.html,£53.74,In stock,1
2,Soumission,soumission_998/index.html,£50.10,In stock,1
3,Sharp Objects,sharp-objects_997/index.html,£47.82,In stock,4
4,Sapiens: A Brief History ...,sapiens-a-brief-history-of-humankind_996/index...,£54.23,In stock,5
...,...,...,...,...,...
995,Alice in Wonderland (Alice's ...,alice-in-wonderland-alices-adventures-in-wonde...,£55.53,In stock,1
996,"Ajin: Demi-Human, Volume 1 ...",ajin-demi-human-volume-1-ajin-demi-human-1_4/i...,£57.06,In stock,4
997,A Spy's Devotion (The ...,a-spys-devotion-the-regency-spies-of-london-1_...,£16.97,In stock,5
998,1st to Die (Women's ...,1st-to-die-womens-murder-club-1_2/index.html,£53.98,In stock,1
999,"1,000 Places to See ...",1000-places-to-see-before-you-die_1/index.html,£26.08,In stock,5

In [16]:
df_all.to_csv("Book_info_all.csv")