In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url="https://www.worldometers.info/world-population/population-by-country/"
r=requests.get(url)
r

In [3]:
soup=BeautifulSoup(r.content,'html.parser')

In [4]:
soup.prettify()

'<!DOCTYPE html>\n<html data-astro-transition-scope="astro-s7reefwf-2" dir="ltr" lang="en">\n <head>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>\n  <meta content="width=device-width, initial-scale=1" name="viewport"/>\n  <title>\n   Population by Country (2026) - Worldometer\n  </title>\n  <!-- <I18nTags /> -->\n  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ZDP3BFSX60">\n  </script>\n  <script>\n   window.dataLayer = window.dataLayer || [];\n  function gtag() {\n    // eslint-disable-next-line prefer-rest-params\n    dataLayer.push(arguments);\n  }\n  gtag("js", new Date());\n  gtag("config", "G-ZDP3BFSX60", {\n    page_lang: document.documentElement.lang,\n  });\n  </script>\n  <script crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3701697624350410">\n  </script>\n  <script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js">\n  </script>\n  <link crossorigin="" href="https://a.pub.network/" rel="preconnect"/>\n  <link crossorigin="" href="https://b.pub.network/" rel="preconnect"/>\n  <link crossorigin="" href="https://c.pub.network/" rel="preconnect"/>\n  <link crossorigin="" href="https://d.pub.network/" rel="preconnect"/>\n  <link crossorigin="" href="https://c.amazon-adsystem.com" rel="preconnect"/>\n  <link crossorigin="" href="https://s.amazon-adsystem.com" rel="preconnect"/>\n  <link crossorigin="" href="https://btloader.com/" rel="preconnect"/>\n  <link crossorigin="" href="https://api.btloader.com/" rel="preconnect"/>\n  <link crossorigin="" href="https://cdn.confiant-integrations.net" rel="preconnect"/>\n  <!-- Below is a link to a CSS file that accounts for Cumulative Layout Shift -->\n  <!-- The file is intended to eliminate the layout shifts that are seen when ads load into the page. If you don\'t want to use this, simply remove this file -->\n  <!-- To find out more about CLS, visit https://web.dev/vitals/ -->\n  <link href="https://a.pub.network/worldometers-info/cls.css" rel="stylesheet"/>\n  <script data-cfasync="false" type="text/javascript">\n   // must be \'var\'\n  /** @type {Freestar} */\n  var freestar = freestar || {};\n\n  freestar.queue = freestar.queue || [];\n\n  freestar.config = freestar.config || {};\n  freestar.config.enabled_slots = [];\n\n  freestar.initCallback = function () {\n    freestar.config.enabled_slots.length === 0\n      ? (freestar.initCallbackCalled = false)\n      : freestar.newAdSlots(freestar.config.enabled_slots);\n  };\n  </script>\n  <script async="" data-cfasync="false" src="https://a.pub.network/worldometers-info/pubfig.min.js">\n  </script>\n  <meta content="en" property="og:locale"/>\n  <meta content="website" property="og:type"/>\n  <meta content="https://www.worldometers.info/world-population/population-by-country/" property="og:url"/>\n  <meta content="Worldometer" property="og:site_name"/>\n  <meta content="Population by Country (2026) - Worldometer" property="og:title"/>\n  <meta content="List of countries and dependencies in the world ranked by population, from the most populated. Growth rate, median age, fertility rate, area, density, population density, urbanization, urban population, share of world population." property="og:description"/>\n  <meta content="https://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>\n  <link href="https://cdn.worldometers.info/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>\n  <link href="https://cdn.worldometers.info/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>\n  <link href="https://cdn.worldometers.info/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>\n  <link href="https://cdn.worldometers.info/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>\n  <link href="https://cdn.worldometers.info/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>\n  <link href="https://cdn.worldometers.info/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>\n  <link href="https://cdn.worldometers.info/favicon/manifest.json" rel="manifest"/>\n  <meta content="#ffffff" name="msapplication-TileColor"/>\n  <meta content="https://cdn.worldometers.info/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>\n  <meta content="#ffffff" name="theme-color"/>\n  <style type="text/css">\n   @font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/greek-ext/wght/normal.woff2);unicode-range:U+1F00-1FFF;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/vietnamese/wght/normal.woff2);unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/latin-ext/wght/normal.woff2);unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/cyrillic/wght/normal.woff2);unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/latin/wght/normal.woff2);unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/greek/wght/normal.woff2);unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/cyrillic-ext/wght/normal.woff2);unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/devanagari/wght/normal.woff2);unicode-range:U+0900-097F,U+1CD0-1CF9,U+200C-200D,U+20A8,U+20B9,U+20F0,U+25CC,U+A830-A839,U+A8E0-A8FF,U+11B00-11B09;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/devanagari/wght/italic.woff2);unicode-range:U+0900-097F,U+1CD0-1CF9,U+200C-200D,U+20A8,U+20B9,U+20F0,U+25CC,U+A830-A839,U+A8E0-A8FF,U+11B00-11B09;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/greek/wght/italic.woff2);unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/latin-ext/wght/italic.woff2);unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/greek-ext/wght/italic.woff2);unicode-range:U+1F00-1FFF;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/latin/wght/italic.woff2);unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/cyrillic/wght/italic.woff2);unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/vietnamese/wght/italic.woff2);unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB;font-display:swap;}@font-face {font-family:\'Noto Sans\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/noto-sans/5.2.10/cyrillic-ext/wght/italic.woff2);unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/latin/wght/normal.woff2);unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/vietnamese/wght/normal.woff2);unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/cyrillic-ext/wght/normal.woff2);unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/greek/wght/normal.woff2);unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/greek-ext/wght/normal.woff2);unicode-range:U+1F00-1FFF;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/cyrillic/wght/normal.woff2);unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:normal;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/latin-ext/wght/normal.woff2);unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/vietnamese/wght/italic.woff2);unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/cyrillic-ext/wght/italic.woff2);unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/latin/wght/italic.woff2);unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/greek-ext/wght/italic.woff2);unicode-range:U+1F00-1FFF;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/cyrillic/wght/italic.woff2);unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/latin-ext/wght/italic.woff2);unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF;font-display:swap;}@font-face {font-family:\'Roboto Condensed\';font-style:italic;font-weight:100 900;src:url(/cf-fonts/v/roboto-condensed/5.2.8/greek/wght/italic.woff2);unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF;font-display:swap;}\n  </style>\n  <meta content="List of countries and dependencies in the world ranked by population, from the most populated. Growth rate, median age, fertility rate, area, density, population density, urbanization, urban population, share of world population." name="description"/>\n  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n  <!--[if lt IE 9]>\n            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>\n            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>\n        <![endif]-->\n  <link href="https://cdn.worldometers.info/assets/style.css" rel="stylesheet"/>\n  <script src="https://cdn.worldometers.info/assets/page.B9k6RjYL.js" type="module">\n  </script>\n  <style>\n   [data-astro-transition-scope="astro-s7reefwf-2"] { view-transition-name: astro-s7reefwf-2; }@layer astro { ::view-transition-old(astro-s7reefwf-2) { animation: none; opacity: 0; mix-blend-mode: normal; }::view-transition-new(astro-s7reefwf-2) { animation: none; mix-blend-mode: normal; }::view-transition-group(astro-s7reefwf-2) { animation: none } }[data-astro-transition-fallback="old"] [data-astro-transition-scope="astro-s7reefwf-2"],\n\t\t\t[data-astro-transition-fallback="old"][data-astro-transition-scope="astro-s7reefwf-2"] { animation: none; mix-blend-mode: normal; }[data-astro-transition-fallback="new"] [data-astro-transition-scope="astro-s7reefwf-2"],\n\t\t\t[data-astro-transition-fallback="new"][data-astro-transition-scope="astro-s7reefwf-2"] { animation: none; mix-blend-mode: normal; }\n  </style>\n </head>\n <body class="font-body text-base">\n  <div class="flex flex-col">\n   <div class="shrink-0">\n    <div x-data="{ open: false, id: \'mobile-menu\' }">\n     <header class="border-b">\n      <nav class="container py-4">\n       <div class="flex items-center justify-between gap-16 md:justify-start">\n        <div class="shrink-0">\n         <a data-astro-reload="" href="/">\n          <img alt="Worldometer Logo" src="https://cdn.worldometers.info/img/worldometers-logo.gif" title="Worldometer" width="200"/>\n         </a>\n        </div>\n        <div class="hidden w-full items-center justify-between md:flex">\n         <div class="flex items-center gap-4">\n          <a class="transition-colors text-muted-foreground hover:text-foreground" data-astro-prefetch="viewport" data-astro-reload="true" href="/population/">\n           Population\n          </a>\n          <div class="relative" data-slot="dropdown-menu" x-data="{\n  open: false,\n  highlightedIndex: -1,\n  items: [],\n  menuId: $id(\'dropdown-menu\'),\n  searchQuery: \'\',\n  searchTimeout: null,\n\n  init() {\n    this.items = Array.from(\n      this.$el.querySelectorAll(\'[data-slot=&quot;dropdown-menu-item&quot;]:not([data-disabled])\')\n    ).map((el, index) =&gt; ({\n      el,\n      label: el.dataset.label || el.textContent?.trim() || \'\',\n      id: this.menuId + \'-item-\' + index\n    }));\n    this.items.forEach((item) =&gt; { item.el.id = item.id; });\n  },\n\n  toggle() {\n    this.open = !this.open;\n    if (this.open) {\n      const trigger = this.$el.querySelector(\'[data-slot=&quot;dropdown-menu-trigger&quot;]\');\n      const content = this.$el.querySelector(\'[data-slot=&quot;dropdown-menu-content&quot;]\');\n      if (trigger &amp;&amp; content) {\n        content.style.setProperty(\'--anchor-width\', trigger.offsetWidth + \'px\');\n      }\n    }\n  },\n\n  close() {\n    this.open = false;\n    this.highlightedIndex = -1;\n    this.$el.querySelector(\'[data-slot=&quot;dropdown-menu-trigger&quot;]\')?.focus();\n  },\n\n  initHighlight() {\n    const activeIndex = this.items.findIndex(item =&gt; item.el.hasAttribute(\'data-active\'));\n    this.highlightedIndex = activeIndex &gt;= 0 ? activeIndex : 0;\n    this.$nextTick(() =&gt; this.scrollToHighlighted());\n  },\n\n  highlightNext() {\n    if (this.highlightedIndex &lt; this.items.length - 1) {\n      this.highlightedIndex++;\n      this.scrollToHighlighted();\n    }\n  },\n\n  highlightPrev() {\n    if (this.highlightedIndex &gt; 0) {\n      this.highlightedIndex--;\n      this.scrollToHighlighted();\n    }\n  },\n\n  highlightFirst() {\n    this.highlightedIndex = 0;\n    this.scrollToHighlighted();\n  },\n\n  highlightLast() {\n    this.highlightedIndex = this.items.length - 1;\n    this.scrollToHighlighted();\n  },\n\n  scrollToHighlighted() {\n    const item = this.items[this.highlightedIndex];\n    if (item?.el) {\n      item.el.scrollIntoView({ block: \'nearest\' });\n      item.el.focus();\n    }\n  },\n\n  typeAhead(char) {\n    this.searchQuery += char.toLowerCase();\n    clearTimeout(this.searchTimeout);\n    this.searchTimeout = setTimeout(() =&gt; { this.searchQuery = \'\'; }, 500);\n    const match = this.items.findIndex(item =&gt;\n      item.label.toLowerCase().startsWith(this.searchQuery)\n    );\n    if (match &gt;= 0) {\n      this.highlightedIndex = match;\n      this.scrollToHighlighted();\n    }\n  }\n}" x-init="init()">\n           <button aria-haspopup="menu" class="group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap font-medium text-sm bg-clip-padding rounded-md border select-none outline-none transition-all [&amp;_svg:not([class*=\'size-\'])]:size-4 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-[3px] aria-invalid:ring-destructive/20 disabled:pointer-events-none disabled:opacity-50 border-border bg-background shadow-xs hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground h-9 px-2.5 in-data-[slot=button-group]:rounded-md has-data-[icon=inline-start]:ps-2 has-data-[icon=inline-end]:pe-2 cursor-pointer" data-slot="dropdown-menu-trigger" type="button" x-bind:aria-expanded="open" x-on:click="toggle()" x-on:keydown="$event.key.length === 1 &amp;&amp; /[a-zA-Z0-9]/.test($event.key) &amp;&amp; typeAhead($event.key)" x-on:keydown.down.prevent="open ? highlightNext() : (open = true, $nextTick(() =&gt; initHighlight()))" x-on:keydown.end.prevent="open &amp;&amp; highlightLast()" x-on:keydown.escape="close()" x-on:keydown.home.prevent="open &amp;&amp; highlightFirst()" x-on:keydown.tab="close()" x-on:ke

In [5]:
col=[]
cols=soup.find('table',class_='datatable').find('thead').find_all('th')
for i in cols:
  col.append(i.text)

In [6]:
col

[' # ',
 ' Country (or dependency) ',
 ' Population 2026 ',
 ' Yearly Change ',
 ' Net Change ',
 ' Density (P/Km²) ',
 ' Land Area (Km²) ',
 ' Migrants (net) ',
 ' Fert. Rate ',
 ' Median Age ',
 ' Urban Pop % ',
 ' World Share ']

In [7]:
table=soup.find('table',class_='datatable').find('tbody').find_all('tr')
table

[<tr id="india"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 1 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/india-population/"> India </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14766255760000" dir="ltr"> 1,476,625,576 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87" dir="ltr"> 0.87% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="127600510000" dir="ltr"> 12,760,051 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4966469" dir="ltr"> 497 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="29731900000" dir="ltr"> 2,973,190 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-4404560000" dir="ltr"> −440,456 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19290" dir="ltr"> 1.93 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292160" dir="ltr"> 29.2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3761" dir="ltr"> 37.6% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1779" dir="ltr"> 17.8% </td> </tr>,
 <tr id="china"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/china-population/"> China </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14129140890000" dir="ltr"> 1,412,914,089 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-22" dir="ltr"> −0.22% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-31820050000" dir="ltr"> −3,182,005 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1504988" dir="ltr"> 150 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="93882110000" dir="ltr"> 9,388,211 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2321070000" dir="ltr"> −232,107 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10310" dir="ltr"> 1.03 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406480" dir="ltr"> 40.6 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6868" dir="ltr"> 68.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1702" dir="ltr"> 17% </td> </tr>,
 <tr id="us"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/us-population/"> United States </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="3490354940000" dir="ltr"> 349,035,494 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="51" dir="ltr"> 0.51% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="17596870000" dir="ltr"> 1,759,687 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="381567" dir="ltr"> 38 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="91474200000" dir="ltr"> 9,147,420 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="11778480000" dir="ltr"> 1,177,848 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="16250" dir="ltr"> 1.63 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="387130" dir="ltr"> 38.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8313" dir="ltr"> 83.1% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="420" dir="ltr"> 4.2% </td> </tr>,
 <tr id="indonesia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 4 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/indonesia-population/"> Indonesia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2878867820000" dir="ltr"> 287,886,782 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="76" dir="ltr"> 0.76% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21655460000" dir="ltr"> 2,165,546 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1589156" dir="ltr"> 159 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18115700000" dir="ltr"> 1,811,570 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-394720000" dir="ltr"> −39,472 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20800" dir="ltr"> 2.08 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="306590" dir="ltr"> 30.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6027" dir="ltr"> 60.3% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="347" dir="ltr"> 3.5% </td> </tr>,
 <tr id="pakistan"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 5 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/pakistan-population/"> Pakistan </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2592997910000" dir="ltr"> 259,299,791 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.6% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="40802370000" dir="ltr"> 4,080,237 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3363686" dir="ltr"> 336 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7708800000" dir="ltr"> 770,880 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-11447380000" dir="ltr"> −1,144,738 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34420" dir="ltr"> 3.44 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="207710" dir="ltr"> 20.8 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3470" dir="ltr"> 34.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="312" dir="ltr"> 3.1% </td> </tr>,
 <tr id="nigeria"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 6 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/nigeria-population/"> Nigeria </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2424318320000" dir="ltr"> 242,431,832 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="206" dir="ltr"> 2.06% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="49040500000" dir="ltr"> 4,904,050 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2661834" dir="ltr"> 266 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9107700000" dir="ltr"> 910,770 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-28100000" dir="ltr"> −2,810 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="42050" dir="ltr"> 4.21 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="183480" dir="ltr"> 18.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="5580" dir="ltr"> 55.8% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292" dir="ltr"> 2.9% </td> </tr>,
 <tr id="brazil"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/brazil-population/"> Brazil </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2135626660000" dir="ltr"> 213,562,666 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="35" dir="ltr"> 0.35% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7502610000" dir="ltr"> 750,261 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="255515" dir="ltr"> 26 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="83581400000" dir="ltr"> 8,358,140 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2056420000" dir="ltr"> −205,642 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="15910" dir="ltr"> 1.59 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="352500" dir="ltr"> 35.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9174" dir="ltr"> 91.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="257" dir="ltr"> 2.6% </td> </tr>,
 <tr id="bangladesh"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 8 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/bangladesh-population/"> Bangladesh </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1778180440000" dir="ltr"> 177,818,044 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="121" dir="ltr"> 1.21% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21311450000" dir="ltr"> 2,131,145 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="13660447" dir="ltr"> 1,366 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1301700000" dir="ltr"> 130,170 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-3713980000" dir="ltr"> −371,398 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20900" dir="ltr"> 2.09 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="263020" dir="ltr"> 26.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4321" dir="ltr"> 43.2% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="214" dir="ltr"> 2.1% </td> </tr>,
 <tr id="russia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 9 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/russia-population/"> Russia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1433944580000" dir="ltr"> 143,394,458 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-42" dir="ltr"> −0.42% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6029350000" dir="ltr"> −602,935 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87559" dir="ltr"> 9 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="163768700000" dir="ltr"> 16,376,870 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3249240000" dir="ltr"> 324,924 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="14700" dir="ltr"> 1.47 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406950" dir="ltr"> 40.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7541" dir="ltr"> 75.4% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="173" dir="ltr"> 1.7% </td> </tr>,
 <tr id="ethiopia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 10 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/ethiopia-population/"> Ethiopia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1389021850000" dir="ltr"> 138,902,185 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="253" dir="ltr"> 2.53% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34301340000" dir="ltr"> 3,430,134 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1389022" dir="ltr"> 139 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10000000000" dir="ltr"> 1,000,000 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="272980000" dir="ltr"> 27,298 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="37230" dir="ltr"> 3.72 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="193410" dir="ltr"> 19.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2290" dir="ltr"> 22.9% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="167" dir="ltr"> 1.7% </td> </tr>,
 <tr id="mexico"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 11 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/mexico-population/"> Mexico </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1329976580000" dir="ltr"> 132,997,658 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="80" dir="ltr"> 0.8% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10507580000" dir="ltr"> 1,050,758 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="684162" dir="ltr"> 68 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19439500000" dir="ltr"> 1,943,950 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-1098440000" dir="ltr"> −109,844 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18520" dir="ltr"> 1.85 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="299950" dir="ltr"> 30 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8830" dir="ltr"> 88.3% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.6% </td> </tr>,
 <tr id="japan"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 12 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/japan-population/"> Japan </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1224277310000" dir="ltr"> 122,427,731 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-55" dir="ltr"> −0.55% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6757480000" dir="ltr"> −675,748 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3358279" dir="ltr"> 336 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3645550000" dir="ltr"> 364,555 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1286190000" dir="ltr"> 128,619 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="12310" dir="ltr"> 1.23 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="501810" dir="ltr"> 50.2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9335" dir="ltr"> 93.4% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="147" dir="ltr"> 1.5% </td> </tr>,
 <tr id="egypt"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 13 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/egypt-population/"> Egypt </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1201011750000" dir="ltr"> 120,101,175 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="147" dir="ltr"> 1.47% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="17351800000" dir="ltr"> 1,735,180 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1206501" dir="ltr"> 121 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9954500000" dir="ltr"> 995,450 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-522870000" dir="ltr"> −52,287 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="26830" dir="ltr"> 2.68 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="246970" dir="ltr"> 24.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4112" dir="ltr"> 41.1% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="145" dir="ltr"> 1.4% </td> </tr>,

In [8]:
table_data=[]
for item in table:
  rows=[]
  row=item.find_all("td")
  for j in row:
    rows.append(j.text)
  table_data.append(rows)

In [13]:
table_data[:2]

[[' 1 ',
  '  India  ',
  ' 1,476,625,576 ',
  ' 0.87% ',
  ' 12,760,051 ',
  ' 497 ',
  ' 2,973,190 ',
  ' −440,456 ',
  ' 1.93 ',
  ' 29.2 ',
  ' 37.6% ',
  ' 17.8% '],
 [' 2 ',
  '  China  ',
  ' 1,412,914,089 ',
  ' −0.22% ',
  ' −3,182,005 ',
  ' 150 ',
  ' 9,388,211 ',
  ' −232,107 ',
  ' 1.03 ',
  ' 40.6 ',
  ' 68.7% ',
  ' 17% ']]

In [10]:
import pandas as pd
import numpy as np
arr=np.array(table_data)
df=pd.DataFrame(arr[:,1:],columns=col[1:])
df.head()

,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","−440,456",1.93,29.2,37.6%,17.8%
1,China,"1,412,914,089",−0.22%,"−3,182,005",150,"9,388,211","−232,107",1.03,40.6,68.7%,17%
2,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.2%
3,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","−39,472",2.08,30.7,60.3%,3.5%
4,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","−1,144,738",3.44,20.8,34.7%,3.1%

In [14]:
df.to_csv("Countries_in_the_world_by_population.csv",index=False)

In [15]:
pd.read_csv("Countries_in_the_world_by_population.csv")

,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","−440,456",1.93,29.2,37.6%,17.8%
1,China,"1,412,914,089",−0.22%,"−3,182,005",150,"9,388,211","−232,107",1.03,40.6,68.7%,17%
2,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.2%
3,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","−39,472",2.08,30.7,60.3%,3.5%
4,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","−1,144,738",3.44,20.8,34.7%,3.1%
...,...,...,...,...,...,...,...,...,...,...,...
229,Montserrat,"4,328",−0.71%,−31,43,100,−10,1.45,41.8,11.7%,0.000052%
230,Falkland Islands,"3,465",−0.12%,−4,0,"12,170",−16,1.69,43.4,68.4%,0.000042%
231,Tokelau,"2,691",3.18%,83,269,10,43,2.54,27.6,–,0.000032%
232,Niue,"1,822",0.05%,1,7,260,2,2.44,35.1,45.2%,0.000022%
233,Holy See,506,1%,5,"1,265",0,13,1.00,56.2,–,0.0000061%